# Generated by Django 5.1.2 on 2024-10-17 15:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Vaga')),
                ('descricao', models.TextField(verbose_name='Descrição da Vaga')),
                ('responsabilidades_atribuicoes', models.TextField(verbose_name='Responsabilidades e atribuições')),
                ('requisitos_qualificacoes', models.TextField(verbose_name='Requisitos e qualificações')),
                ('informacoes_adicionais', models.TextField(blank=True, null=True, verbose_name='Informações adicionais')),
                ('sobre_empresa', models.TextField(verbose_name='Sobre a Empresa')),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Publicação')),
                ('data_encerramento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Encerramento')),
                ('status', models.CharField(choices=[('CRIADA', 'Criada'), ('PUBLICADA', 'Publicada'), ('ENCERRADA', 'Encerrada')], default='CRIADA', max_length=10, verbose_name='Status')),
                ('modalidade', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('REMOTO', 'Remoto'), ('HIBRIDO', 'Híbrido')], max_length=10, verbose_name='Modalidade')),
                ('pcd', models.CharField(choices=[('SOMENTE_PCD', 'Somente PCD'), ('NAO_PCD', 'Somente não PCD'), ('QUALQUER', 'Qualquer')], max_length=15, verbose_name='PCD')),
                ('remuneracao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Remuneração')),
                ('empresa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
            },
        ),
    ]
