# Generated by Django 5.1.2 on 2024-10-17 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaga',
            old_name='empresa_id',
            new_name='empresa',
        ),
    ]
