# Generated by Django 5.1.2 on 2024-11-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0003_candidatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatura',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10, verbose_name='Status'),
        ),
    ]
