# Generated by Django 5.1.2 on 2024-10-31 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareds', '0003_cepsourceapi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telefone',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='telefone',
            name='object_id',
        ),
        migrations.AddField(
            model_name='telefone',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to=settings.AUTH_USER_MODEL),
        ),
    ]
