# Generated by Django 5.1.2 on 2024-10-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idioma',
            name='nivel',
            field=models.CharField(choices=[('Básico', 'Básico'), ('Intermediário', 'Intermediário'), ('Avançado', 'Avançado')], max_length=20, verbose_name='Nível'),
        ),
    ]
