# Generated by Django 5.1.2 on 2024-11-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0003_alter_idioma_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadoscandidato',
            name='curriculo',
            field=models.ImageField(blank=True, null=True, upload_to='curriculos/', verbose_name='Currículo'),
        ),
    ]
