# Generated by Django 5.1.2 on 2024-11-05 17:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0005_remove_dadoscandidato_curriculo_curriculo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculo',
            name='titulo_curriculo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Título Currículo'),
        ),
        migrations.AlterUniqueTogether(
            name='habilidade',
            unique_together={('usuario', 'nome')},
        ),
    ]
