# Generated by Django 5.1.2 on 2024-11-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0006_curriculo_titulo_curriculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienciaacademica',
            name='status',
            field=models.CharField(choices=[('Completo', 'Completo'), ('Incompleto', 'Incompleto'), ('Interrompido', 'Interrompido'), ('em_andamento', 'Em andamento')], default='Em andamento', max_length=20, verbose_name='Status'),
        ),
    ]
