# Generated by Django 5.1.2 on 2024-11-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0010_alter_idioma_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadoscandidato',
            name='tipo_deficiencia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de Deficiência'),
        ),
    ]
