# Generated by Django 5.1.2 on 2024-10-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=255, verbose_name='Nome da Empresa')),
                ('email_corporativo', models.EmailField(max_length=255, verbose_name='Email Corporativo')),
                ('site_empresa', models.URLField(blank=True, verbose_name='Site da Empresa')),
                ('linkedin_empresa', models.URLField(blank=True, verbose_name='LinkedIn da Empresa')),
                ('instagram_empresa', models.URLField(blank=True, verbose_name='Instagram da Empresa')),
                ('numero_funcionarios', models.IntegerField(blank=True, null=True, verbose_name='Número de Funcionários')),
                ('segmento_empresa', models.CharField(max_length=255, verbose_name='Segmento da Empresa')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
                ('logo', models.ImageField(blank=True, upload_to='logos/', verbose_name='Logo')),
                ('banner', models.ImageField(blank=True, upload_to='banners/', verbose_name='Banner')),
                ('informacoes_empresa', models.TextField(blank=True, verbose_name='Informações da Empresa')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
