# Generated by Django 5.1.2 on 2024-10-31 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='representante',
        ),
        migrations.AddField(
            model_name='empresa',
            name='responsavel',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Reponsável'),
            preserve_default=False,
        ),
    ]
