# Generated by Django 5.1.2 on 2024-11-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_alter_empresa_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='informacoes_empresa',
            field=models.TextField(blank=True, null=True, verbose_name='Informações da Empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='instagram_empresa',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram da Empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='linkedin_empresa',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn da Empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='site_empresa',
            field=models.URLField(blank=True, null=True, verbose_name='Site da Empresa'),
        ),
    ]
