# Generated by Django 5.1.2 on 2024-10-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tipo',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('candidato', 'Candidato'), ('representante', 'Representante de Empresa')], default='candidato', max_length=15, verbose_name='Tipo de Usuário'),
        ),
    ]
