# Generated by Django 5.1.2 on 2024-11-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='username'),
        ),
    ]
