# Generated by Django 5.1.2 on 2024-11-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_is_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('funcionario', 'Funcionário'), ('candidato', 'Candidato'), ('responsavel', 'Responsável de Empresa')], max_length=15, verbose_name='Tipo de Usuário'),
        ),
    ]
