# Generated by Django 5.1.2 on 2024-11-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('funcionario', 'Funcionário'), ('candidato', 'Candidato'), ('responsavel', 'Responsável de Empresa')], default='candidato', max_length=15, verbose_name='Tipo de Usuário'),
        ),
    ]
