# Generated by Django 5.1.2 on 2024-11-26 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_customuser_tipo'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
